{
 "title": "isucon-nginx",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Operation",
    "label": "Operation",
    "query": "SELECT DISTINCT(Operation) FROM nginx_accesses"
   }
  ]
 },
 "panels": [
  {
   "title": "nginx: Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as \"time\", Operation, count(*) as Requests FROM \"otel\".\"nginx_accesses\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( Operation IN ($Operation) ) GROUP BY Operation, time ORDER BY time ASC LIMIT 100000"
    }
   ]
  },
  {
   "title": "nginx: p90 Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as \"time\", Operation, quantile(0.9)(Duration) FROM \"otel\".\"nginx_accesses\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( Operation IN ($Operation) ) GROUP BY Operation, time ORDER BY time ASC LIMIT 100000"
    }
   ]
  },
  {
   "title": "nginx: Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"TraceId\" as traceID, \"ServiceName\" as serviceName, \"SpanName\" as operationName, \"Timestamp\" as startTime, multiply(\"Duration\", 0.000001) as duration FROM \"otel\".\"otel_traces_normalized\" WHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) AND ( ParentSpanId = '' ) AND ( Duration > 0 ) AND ( ServiceName = 'nginx' ) AND ( SpanName IN ($Operation) ) ORDER BY Timestamp DESC, Duration DESC LIMIT 1000"
    }
   ]
  },
  { "title": "Stats for all operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "nginx: Request count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Operation, count(*) FROM \"otel\".\"nginx_accesses\" WHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) GROUP BY Operation ORDER BY count(*) DESC LIMIT 10000"
    }
   ]
  },
  {
   "title": "nginx: Sum response time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Operation, sum(Duration) FROM \"otel\".\"nginx_accesses\" WHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) GROUP BY Operation ORDER BY sum(Duration) DESC LIMIT 10000"
    }
   ]
  },
  {
   "title": "nginx: Average response time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Operation, avg(Duration) FROM \"otel\".\"nginx_accesses\" WHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) GROUP BY Operation ORDER BY avg(Duration) DESC LIMIT 10000"
    }
   ]
  },
  {
   "title": "nginx: p90 response time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Operation, quantile(0.9)(Duration) FROM \"otel\".\"nginx_accesses\" WHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) GROUP BY Operation ORDER BY quantile(0.9)(Duration) DESC LIMIT 10000"
    }
   ]
  },
  {
   "title": "app: journald isuride-go log",
   "type": "logs",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT Timestamp as \"timestamp\", Message as \"body\", SeverityText as \"level\", Hostname FROM \"otel\".\"chi_log\" WHERE ( timestamp >= $__fromTime AND timestamp <= $__toTime AND SeverityText != 'INFO') ORDER BY timestamp DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "nginx: error log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT Timestamp as \"timestamp\", Body as \"body\", SeverityText as \"level\", LogAttributes as \"labels\", TraceId as \"traceID\" FROM \"otel\".\"otel_logs\" WHERE ( timestamp >= $__fromTime AND timestamp <= $__toTime ) AND ( LogAttributes['log.file.name'] = 'error.log' ) ORDER BY timestamp DESC LIMIT 1000"
    }
   ]
  }
 ]
}