{
 "title": "isucon-pt-query-digest",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Operation",
    "label": "Operation",
    "query": "SELECT DISTINCT(Operation) FROM nginx_accesses"
   }
  ]
 },
 "panels": [
  {
   "title": "nginx: Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as \"time\", Operation, count(*) as Requests FROM \"otel\".\"nginx_accesses\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( Operation IN ($Operation) ) GROUP BY Operation, time ORDER BY time ASC LIMIT 100000"
    }
   ]
  },
  {
   "title": "pt-query-digest: Result batch timeline",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as \"time\", Fingerprint, sum(Count) FROM \"otel\".\"pt_query_digest_log\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY Fingerprint, time ORDER BY time ASC LIMIT 10000"
    }
   ]
  },
  {
   "title": "pt-query-digest: Results",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT Fingerprint, avg(AvgQueryTime), avg(P95QueryTime), sum(Count), sum(SumQueryTime) FROM \"otel\".\"pt_query_digest_log\" WHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) GROUP BY Fingerprint ORDER BY sum(SumQueryTime) DESC LIMIT 10000"
    }
   ]
  },
  {
   "title": "pt-query-digest: Results 2",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT Fingerprint, FIRST_VALUE(Example), Database, sum(SumQueryTime)  FROM \"otel\".\"pt_query_digest_log\" WHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) GROUP BY Fingerprint, Database ORDER BY sum(SumQueryTime) DESC LIMIT 1000"
    }
   ]
  }
 ]
}