ISUCON_DB_HOST="isucon3"
ISUCON_DB_PORT="3306"
ISUCON_DB_USER="isucon"
ISUCON_DB_PASSWORD="isucon"
ISUCON_DB_NAME="isuride"

# マッチング間隔（秒）
ISUCON_MATCHING_INTERVAL=0.5

GOOGLE_APPLICATION_CREDENTIALS=/home/isucon/service-account-credentials.json
GOOGLE_CLOUD_PROJECT=triple-innocent

OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="http://localhost:4317"
